### ISSUE TITLE
Maybe missing parts in README.md

### ISSUE THREAD

**Issue by Krutsch** [jaredLunde/snowpack-plugin-imagemin#2]
Hey, 
I tried it in my repo and it does not work. I followed the instructions though.
I have one image in the ./src folder that I would like to optimize.
Could you take a quick look and help me out?🤩

[Repository](https://github.com/Krutsch/snowpack-image)

**Comment by jaredLunde** [comment]
It for sure works

**Comment by jaredLunde** [comment]
Here’s a repo. Figure it out. https://github.com/jaredLunde/blog/blob/master/snowpack.config.js
